<table>
    <tr>
        <td width="320">
            <img style="width:240px;" width="240" src="<?php echo $this->getViewFileUrl('Fwc_SAREhub::images/logo.png'); ?>"/>
        </td>
        <td style="text-align: left;">
            <?php echo __('Version');?>: 0.1.0<br/>
            <?php echo __('Documentation');?>:<br/>
            <?php echo __('More info');?>: <a href="https://sarehub.com/" target="_blank">https://sarehub.com/</a>
        </td>
    </tr>
</table>
